name: Deploy Terraform Backend and OIDC

on:
  workflow_dispatch:
    inputs:
      region:
        description: "AWS Region"
        required: false
        default: "us-east-1"
      S3BucketName:
        description: The name of the S3 bucket to be created for storing Terraform state files.
        required: false
        default: "gitops-2024-tf-backend"
      DynamoDBTableName:
        description: The name of the DynamoDB table to be created for Terraform state locking.
        required: false
        default: "Gitops2024TerraformLocks"

jobs:
  cluster:
    name: Deploy Terraform backend to AWS
    runs-on: ubuntu-latest
    outputs:
      env-name: ${{ steps.env-name.outputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.region}}

      - name: Configure environment name
        id: env-name
        env:
          REPO: ${{ github.repository }}
        run: |
          ENVIRONMENT=`echo $REPO | tr "/" "-"`
          echo "Environment name: $ENVIRONMENT"
          echo "environment=$ENVIRONMENT" >> $GITHUB_OUTPUT

      - name: Deploy S3 Backend
        id: se-backend
        uses: aws-actions/aws-cloudformation-github-deploy@master
        with:
          name: ${{ steps.env-name.outputs.environment }}-s3
          template: ./cfn/backend-resources.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            S3BucketName=${{ github.event.inputs.S3BucketName }},
            DynamoDBTableName=${{ github.event.inputs.DynamoDBTableName }}

      - name: Deploy OIDC Setup
        id: oidc
        uses: aws-actions/aws-cloudformation-github-deploy@master
        with:
          name: ${{ steps.env-name.outputs.environment }}-oidc
          template: ./cfn/oidc-role.yaml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: >-
            Repo=${{ github.repository }}
